apiVersion: v1
kind: Pod
metadata:
  name: ubuntuapp-az
  labels:
    app: ubuntuapp-az
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "admin", "name":"VN-02"}'
  }
spec:
  nodeSelector:
    "kubernetes.io/hostname": "compute-contrail-az-1"
  containers:
    - name: ubuntuapp
      image: ubuntu-upstart