apiVersion: v1
kind: Pod
metadata:
  name: ubuntuapp-aws
  labels:
    app: ubuntuapp-aws
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "admin", "name":"VN-01"}'
  }
spec:
  nodeSelector:
    "kubernetes.io/hostname": "ip-192-168-0-97.us-west-1.compute.internal"
  containers:
    - name: ubuntuapp
      image: ubuntu-upstart